### ISSUE TITLE
Update license once 2024 comes out

### ISSUE THREAD

**Issue by traversaro** [conda-forge/cppad-feedstock#22]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

See https://github.com/conda-forge/cppad-feedstock/issues/19#issuecomment-1870180232 .

### Installed packages

```shell
,
```

### Environment info

```shell
.
```

**Comment by bradbell** [comment]
1. cppad-20240000.0 is available
3. The following file is an example of how I build and test CppAD on Fedora 
   https://src.fedoraproject.org/rpms/cppad/blob/rawhide/f/cppad.spec
   Please feel free to contact me if you have trouble understand it; e.g., how to create a recipe/run_test.sh for this project.
   The documentation for the 20240000 version of the cmake command can be found at
   https://cppad.readthedocs.io/stable-20240000/cmake.html
   The documentation for xrst (which is used to build the CppAD documentation) can be found at
   https://xrst.readthedocs.io/latest/
4. I have included a build of the CppAD documentation for 2024, as well and the latest version on ReadTheDocs; see
   https://cppad.readthedocs.io/latest/
   https://cppad.readthedocs.io/stable-20240000/

**Comment by traversaro** [comment]
Thanks @bradbell, I updated the license and added running the tests as part of the build in https://github.com/conda-forge/cppad-feedstock/pull/24 .

The linux tests are failing with:
~~~
[  4%] Built target check_speed_cppad
[  4%] Building CXX object speed/cppad_jit/CMakeFiles/speed_cppad_jit.dir/__/main.cpp.o
[  4%] Building CXX object speed/cppad_jit/CMakeFiles/speed_cppad_jit.dir/det_lu.cpp.o
[  5%] Building CXX object speed/cppad_jit/CMakeFiles/speed_cppad_jit.dir/det_minor.cpp.o
[  5%] Building CXX object speed/cppad_jit/CMakeFiles/speed_cppad_jit.dir/mat_mul.cpp.o
[  5%] Building CXX object speed/cppad_jit/CMakeFiles/speed_cppad_jit.dir/ode.cpp.o
[  5%] Building CXX object speed/cppad_jit/CMakeFiles/speed_cppad_jit.dir/poly.cpp.o
[  5%] Building CXX object speed/cppad_jit/CMakeFiles/speed_cppad_jit.dir/sparse_hessian.cpp.o
[  5%] Building CXX object speed/cppad_jit/CMakeFiles/speed_cppad_jit.dir/sparse_jacobian.cpp.o
[  6%] Linking CXX executable speed_cppad_jit
[  6%] Built target speed_cppad_jit
cppad_jit_det_lu_available = false
sh: gcc: command not found
link_det_minor: err_msg = create_dll_lib: following system comamnd failed
gcc -c -fPIC -O2 gradient_det.c -o /tmp/fileIk4S2z
/bin/sh: line 1:  1414 Segmentation fault      (core dumped) ./speed_cppad_jit correct 54321
make[3]: *** [speed/cppad_jit/CMakeFiles/check_speed_cppad_jit.dir/build.make:70: speed/cppad_jit/CMakeFiles/check_speed_cppad_jit] Error 139
make[2]: *** [CMakeFiles/Makefile2:2837: speed/cppad_jit/CMakeFiles/check_speed_cppad_jit.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:909: CMakeFiles/check.dir/rule] Error 2
make: *** [Makefile:169: check] Error 2
~~~

I guess that the problem is that ccpad assumes that the `gcc` binary is available in the path, while in conda-forge the compiler has a different name, that is typically specified to build scripts via the `CC` (for C) or `CXX` (for C++) environment variables.

**Comment by traversaro** [comment]
Probably the easiest fix is to exclude for now the cppad_jit tests by commenting out https://github.com/coin-or/CppAD/blob/20240000.1/speed/CMakeLists.txt#L14 .

**Comment by bradbell** [comment]
As a temporary fix, can you create an alias for gcc command for the testing. In general, the git compile should be using the C compiler that cmake found.

**Comment by bradbell** [comment]
I am not sure how we should fix this but here is the problem:

CppAD detects that gcc is the C compiler as follows:
https://github.com/coin-or/CppAD/blob/master/include/cppad/CMakeLists.txt
```
IF( "${CMAKE_C_COMPILER_ID}" STREQUAL "GNU" )
   SET(cppad_c_compiler_gnu 1)
ELSE()
   SET(cppad_c_compiler_gnu 0)
ENDIF()
```
It then uses this for the jit compiler examples as follows:
https://github.com/coin-or/CppAD/blob/master/example/jit/compile.cpp
```
# if CPPAD_C_COMPILER_GNU
   flag = std::system("gcc --version > temp");
   if( flag == 0 )
      compile = "gcc -c -fPIC -O2";
# endif

**Comment by bradbell** [comment]
Just a heads up here. I am having some trouble with the Fedora build. They have included a 32-bit linux system.

I fixed a problem due to  ``unsigned int`` and ``size_t`` being the same type. I fixed that with cppad-20240000.1. But now I have run into another problem on this system. The CppAD allocation routine is detecting that doubles are not aligned and I need to fix that (or it will be slow); see then end of
https://kojipkgs.fedoraproject.org//work/tasks/5973/111475973/build.log

**Comment by traversaro** [comment]
> In general, the git compile should be using the C compiler that cmake found.

I am not sure about this. I think this could work for files that are only used for tests like https://github.com/coin-or/CppAD/blob/master/example/jit/compile.cpp, however it will not work for files like https://github.com/coin-or/CppAD/blob/3636ba8fd7eeca16522a1dc6cd465cd4f4eb218c/include/cppad/utility/create_dll_lib.hpp#L115C22-L115C25 that are distributed as part of the library, as in general (at least in the conda world) it is perfectly possible that the compiler (specified with full path) that exists in the machine in which the package is built does not exists on the machine in which the binary package is used. A more robust mechanism I think could be to mimick what cmake or autotools do, so use `$CC` if it is defined, of fallback to `gcc` if `$CC` is not defined. This could be do but a code such as:

~~~cxx
std::string gcc_compiler_command;
const char* cc_env_var = std::getenv("CC");
if (cc_env_var) {
    gcc_compiler_command = cc_env_var;
} else {
    // CC environment variable is not defined, fallback to gcc
    gcc_compiler_command = "gcc";
}
compile = gcc_compiler_command + " -c -fPIC -O2";
~~~

probably this logic can also moved in some utility function to avoid duplicating it around.

**Comment by traversaro** [comment]
By the way, we also have a failure in macos (amd64 arch, https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=854549&view=logs&jobId=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b), not sure if this is related to the problem you are seeing:
~~~
[ 61%] Building CXX object example/json/CMakeFiles/example_json.dir/json.cpp.o
[ 61%] Building CXX object example/json/CMakeFiles/example_json.dir/mul_op.cpp.o
[ 61%] Building CXX object example/json/CMakeFiles/example_json.dir/pow_op.cpp.o
[ 62%] Building CXX object example/json/CMakeFiles/example_json.dir/print_op.cpp.o
print_op            OK
sparse              OK
sub_op              OK
sum_op              OK
to_json             OK
unary_op            OK
memory_leak         Error
1 tests failed.
End test group example/json
make[3]: *** [example/json/CMakeFiles/check_example_json] Error 1
make[2]: *** [example/json/CMakeFiles/check_example_json.dir/all] Error 2
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
make: *** [check] Error 2
~~~

**Comment by bradbell** [comment]
Is it possible in the case above that the system is using microsoft DLL's instead of unix dlls and that is causing the problem ? (Microsoft DLLS handel global variables differently.)

**Comment by traversaro** [comment]
> Is it possible in the case above that the system is using microsoft DLL's instead of unix dlls and that is causing the problem ? (Microsoft DLLS handel global variables differently.)

The case above is macOS, not sure if there are any microsoft DLL's  involved. The Windows tests passed fine.

**Comment by bradbell** [comment]
cmake detects windows and uses static instead of dynamic linking (because of the DLL problem).
You could try rerunning the test with cmake specifying static dlls; see cppad-static-lib on
https://cppad.readthedocs.io/stable-20240000/cmake.html#cppad-static-lib

**Comment by bradbell** [comment]
I installed conda on my mac, cloned the current cppad.git, checked out stable/20240000, and added come debugging print to include/cppad/CMakeLists.txt. The result was
```
-- CMAKE_C_COMPILER_ID = AppleClang
```
So the check 
```
IF( "${CMAKE_C_COMPILER_ID}" STREQUAL "Clang" )
```
is failing. What do you suggest for determining if the compiler is Clang, Gnu, or MSVC ?

**Comment by traversaro** [comment]
> What do you suggest for determining if the compiler is Clang, Gnu, or MSVC ?

A SO answer in https://stackoverflow.com/questions/10046114/in-cmake-how-can-i-test-if-the-compiler-is-clang suggests to use `CMAKE_CXX_COMPILER_ID MATCHES "Clang"`. However, note that the CI in this package actually use the conda-forge compiled packages that are installed by the `compilers` package, so I guess that if you use those the `CMAKE_CXX_COMPILER_ID` should be Clang, `AppleClang` is tipically used for the compilers that ship with Xcode.

**Comment by bradbell** [comment]
I was able to solve the remaining  problem with the build on fedora for 32 bit systems. See
https://src.fedoraproject.org/rpms/cppad/c/592496bf4b1cc26796dd02bf37524f3be8a83b34?branch=rawhide

I am going to try and fix the problems above in a CppAD-20240000.2 release

**Comment by bradbell** [comment]
> `AppleClang` is tipically used for the compilers that ship with Xcode.

It appears that I was using the Xcode version of Clang (and gcc); 
```
~>source ~/miniconda/bin/activate
(base) ~>which clang
/usr/bin/clang
(base) ~>which gcc
/usr/bin/gcc
```
I was able to get the tests to pass for the Xcode version using more general logic for detecting clang.
I was also able to install clang using conda and got the tests to pass the tests.

**Comment by bradbell** [comment]
I have run into trouble trying to fix the cc alias for gcc. My solution was to use CMAKE_C_COMPILER to identify the C compiler to use for DLL testing. This ended up with errors on some of the CppAD conda workflow tests. For example, in one case the C compiler cannot find the math.h file; see conda-windows-clang.yml
https://github.com/coin-or/CppAD/actions/runs/7490011815
```
gradient_det.c:3:11: fatal error: 'math.h' file not found
# include <math.h>
          ^~~~~~~~
[ 82%] Building CXX object test_more/deprecated/atomic_two/CMakeFiles/test_more_deprecated_atomic_two.dir/reciprocal.cpp.o
1 error generated.
link_det_minor: err_msg = create_dll_lib: following system command failed
/Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -c -fPIC -O2 gradient_det.c -o /var/tmp/tmp.0.Cf2y1O
```

**Comment by bradbell** [comment]
I think I have fixed the problems mentioned above in the following release:
https://github.com/coin-or/CppAD/archive/20240000.2.tar.gz

There were lots of things that needed fixing to get the jit examples and tests to run on all the workflows. See the stable/20240000 branch on
https://github.com/coin-or/CppAD/actions

One thing I would like to mention is that I added `-D cppad_static_lib=TRUE` to the cmake command for all the builds that use windows DLLS.

**Comment by jcarpent** [comment]
@traversaro may we close this issue?

**Comment by bradbell** [comment]
1. The following location is for an old version, cppad-20221105,  before it was converted from OMhelp to Sphinx (actually the xrst Sphinx wrapper):
https://coin-or.github.io/CppAD
This is referenced in README.md and recipe/meta.yaml

2. In meta.yaml I think you should change `20230000.0` to `20240000.7` (Note that the number after the decimal increases with each bug fix but no new features are added) . The corresponding documentation can be found at 
https://cppad.readthedocs.io/stable-20240000/
You can find a complete list of the cppad releases at
https://github.com/coin-or/CppAD/tags

3. The documentation for the latest version of the master branch can be found at
https://cppad.readthedocs.io/latest/

5. The SPDX license identifier for CppAD is  EPL-2.0 OR GPL-2.0-or-later but I do not know if conda can handle this; see
Secondary License on
https://www.eclipse.org/legal/epl-2.0/faq/#epl-secondary

6. When I run 
```
./build-locally.py >& build-locally.out
tail build-locally.out
```
I get the following output
```
Traceback (most recent call last):
  File "/home/bradbell/repo/cppad-feedstock.git/./build-locally.py", line 105, in <module>
    main()
  File "/home/bradbell/repo/cppad-feedstock.git/./build-locally.py", line 93, in main
    run_docker_build(ns)
  File "/home/bradbell/repo/cppad-feedstock.git/./build-locally.py", line 29, in run_docker_build
    subprocess.check_call([script])
  File "/usr/lib64/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.scripts/run_docker_build.sh']' returned non-zero exit status 1.
```
If I run `grep WARNING build-locally.out` I get
```
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
+ echo 'WARNING: DOCKER_IMAGE variable not set and shyaml not installed. Trying to parse with coreutils'
WARNING: DOCKER_IMAGE variable not set and shyaml not installed. Trying to parse with coreutils
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
WARNING: Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
cppad-feedstock.git>grep WARNING build-locally.out
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
+ echo 'WARNING: DOCKER_IMAGE variable not set and shyaml not installed. Trying to parse with coreutils'
WARNING: DOCKER_IMAGE variable not set and shyaml not installed. Trying to parse with coreutils
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
WARNING: Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
```

**Comment by traversaro** [comment]
> @traversaro may we close this issue?

No, apparently the license is still not updated, I will update it in a dedicated PR.

**Comment by traversaro** [comment]
> 
>     5. When I run
> 
> 
> ```
> ./build-locally.py >& build-locally.out
> tail build-locally.out
> ```
> 
> I get the following output
> 
> ```
> Traceback (most recent call last):
>   File "/home/bradbell/repo/cppad-feedstock.git/./build-locally.py", line 105, in <module>
>     main()
>   File "/home/bradbell/repo/cppad-feedstock.git/./build-locally.py", line 93, in main
>     run_docker_build(ns)
>   File "/home/bradbell/repo/cppad-feedstock.git/./build-locally.py", line 29, in run_docker_build
>     subprocess.check_call([script])
>   File "/usr/lib64/python3.12/subprocess.py", line 413, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['.scripts/run_docker_build.sh']' returned non-zero exit status 1.
> ```
> 
> If I run `grep WARNING build-locally.out` I get
> 
> ```
> WARNING: bridge-nf-call-iptables is disabled
> WARNING: bridge-nf-call-ip6tables is disabled
> + echo 'WARNING: DOCKER_IMAGE variable not set and shyaml not installed. Trying to parse with coreutils'
> WARNING: DOCKER_IMAGE variable not set and shyaml not installed. Trying to parse with coreutils
> WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
> WARNING: Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
> WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
> cppad-feedstock.git>grep WARNING build-locally.out
> WARNING: bridge-nf-call-iptables is disabled
> WARNING: bridge-nf-call-ip6tables is disabled
> + echo 'WARNING: DOCKER_IMAGE variable not set and shyaml not installed. Trying to parse with coreutils'
> WARNING: DOCKER_IMAGE variable not set and shyaml not installed. Trying to parse with coreutils
> WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
> WARNING: Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
> WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
> ```

Which docker version are you using? For which architectural are you building (i.e. the question asked by the script).

**Comment by traversaro** [comment]
Everything else in @bradbell comment should be addressed in https://github.com/conda-forge/cppad-feedstock/pull/34 .

**Comment by bradbell** [comment]
@traversaro
docker --version
Docker version 27.3.1, build ce12230

**Comment by traversaro** [comment]
Can you report the full `build-locally.out` instead of just the tail?

**Comment by bradbell** [comment]
> Can you report the full `build-locally.out` instead of just the tail?

[build-locally.txt](https://github.com/user-attachments/files/17091043/build-locally.txt)
